#!bin/bash
set -e
set -u

echo "Checking that lightning submission works on VM"

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

cd ~
rm -rf src README punter install

tar xvf icfp2017/submissions/lightning/icfp-2e565773-019e-4210-8a37-e9ad58a417ab.tar.gz
./install
lamduct --game-port 9030 --log-level 3 --client-instance-logfile /dev/stderr ./punter

